import { parse } from "csv-parse/sync";
import fs from "fs";
import JSON5 from "json5";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const openingsPath = path.join(__dirname, "lichess-openings-ko.tsv");
const outputPath = path.join(__dirname, "../../__generated/openings.ts");

const openingsContent = fs.readFileSync(openingsPath, "utf-8");

const openingsRecords = parse<Record<string, string>>(openingsContent, {
  delimiter: "\t",
  columns: true,
  skip_empty_lines: true,
});

const openings = openingsRecords.map((record, index) => {
  if (
    !record.eco ||
    !record.name ||
    !record.name_ko ||
    !record.pgn ||
    !record.uci ||
    !record.epd
  ) {
    throw new Error(
      `Invalid opening data at line ${index + 2}: missing required fields`,
    );
  }
  return {
    eco: record.eco,
    name: record.name,
    name_ko: record.name_ko,
    pgn: record.pgn,
    uci: record.uci,
    epd: record.epd,
    moveCount: record.uci.split(" ").length,
  };
});

type Opening = {
  eco: string;
  name: string;
  name_ko: string;
  pgn: string;
  uci: string;
  epd: string;
  moveCount: number;
};

const openingsMapObj: Record<string, Omit<Opening, "epd">> = {};
openings.forEach((opening) => {
  openingsMapObj[opening.epd] = {
    eco: opening.eco,
    name: opening.name,
    name_ko: opening.name_ko,
    pgn: opening.pgn,
    uci: opening.uci,
    moveCount: opening.moveCount,
  };
});

const tsContent = `// @ts-nocheck
// This file is generated by scripts/lichess-openings/generate-lichess-openings.ts
// Do not edit this file manually

export type Opening = {
  eco: string;
  name: string;
  name_ko: string;
  pgn: string;
  uci: string;
  epd: string;
  moveCount: number;
};

export const OPENINGS = ${JSON5.stringify(openings)} as const;

export const OPENING_MAP = ${JSON5.stringify(openingsMapObj)} as const;\n`;

const outputDir = path.dirname(outputPath);
fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(outputPath, tsContent);

console.log(`Generated __generated/openings.ts (${openings.length} openings)`);
